version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.11@sha256:956e4063d7e6365eac95f0894efc3fc88bb8fd36ce613469eb73b960800b6134
    steps:
      - checkout
      - restore_cache:
          key: speedy-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing npm packages
          command: npm install
      - run: 
          name: Build
          command: npm run build
      - save_cache:
          key: speedy-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:16.11@sha256:956e4063d7e6365eac95f0894efc3fc88bb8fd36ce613469eb73b960800b6134
    steps:
      - checkout
      - restore_cache:
          key: speedy-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing npm packages
          command: npm install
      - run: 
          name: Test
          command: npm t
      - save_cache:
          key: speedy-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - test